FarmFreshMarket_213590Z/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace FarmFreshMarket_213590Z.Models
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string? Token { set; get; }
        public bool RememberMe { get; set; } = false;
    }
}

FarmFreshMarket_213590Z/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FarmFreshMarket_213590Z.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

FarmFreshMarket_213590Z/Pages/Login.cshtml.cs
using FarmFreshMarket_213590Z.Models;
using FarmFreshMarket_213590Z.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Web.Lib;

namespace FarmFreshMarket_213590Z.Pages
{

    public class LoginModel : PageModel
    {


        private readonly SignInManager<AuthUser> _signInManager;
        private readonly UserManager<AuthUser> _userManager;
        //session
        private readonly IHttpContextAccessor _httpContextAccessor;

        private readonly GoogleCaptchaService _captchaservice;
        public LoginModel(SignInManager<AuthUser> signInManager, IHttpContextAccessor httpContextAccessor, GoogleCaptchaService captchaservice, UserManager<AuthUser> userManager)
        {
            _signInManager = signInManager;
            //session
            _httpContextAccessor = httpContextAccessor;
            _captchaservice = captchaservice;
            _userManager = userManager;
        }

        [BindProperty]
        public Login LModel { get; set; }


        [AllowAnonymous]
        public void OnGet()
        {

        }

        /*public async Task Login()
        {
            await HttpContext.ChallengeAsync(GoogleDefaults.AuthenticationScheme, new AuthenticationProperties()
            {
                RedirectUri = Url.Action("OnPostGoogle")

            });
            Task Challenge(_signInManager.ConfigureExternalAuthenticationProperties("Google", "/GoogleLogin"), "Google");
        }*/

        public async Task<IActionResult> OnPostGoogle()
        {
            return Challenge(_signInManager.ConfigureExternalAuthenticationProperties("Google", "/GoogleLogin"), "Google");
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            var claims = result.Principal.Identities.FirstOrDefault().Claims.Select(claim => new
            {
                claim.Issuer,
                claim.OriginalIssuer,
                claim.Type,
                claim.Value
            });
            return (IActionResult)claims;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostInHouse()
        {


            if (!ModelState.IsValid)
            {
                Console.WriteLine("Model is INVALID");
                return Page();
            }

            Console.WriteLine("Signing in");
            var identityResult = await _signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, true);
            if (identityResult.Succeeded)
            {
                Console.WriteLine("Success");


                _httpContextAccessor.HttpContext.Session.SetString(SessionVariable.UserName, LModel.Email);

                return RedirectToPage("Index");
            }
            // Account lockout
            else if (identityResult.IsLockedOut)
            {
                //var forgotPassLink = Url.Action(nameof(ForgotPassword), "Account", new { }, Request.Scheme);
                //var content = string.Format("Your account is locked out, to reset your password, please click this link: {0}", forgotPassLink);
                //var message = new Message(new string[] { userModel.Email }, "Locked out account information", content, null);
                //await _emailSender.SendEmailAsync(message);
                ModelState.AddModelError("", "The account is locked out");
                return Page();
            }
            Console.WriteLine("Failed");
            ModelState.AddModelError(nameof(LModel.Email), "Username or Password is incorrect");
            return Page();
        }





    }
}

FarmFreshMarket_213590Z/Pages/Logout.cshtml.cs
using FarmFreshMarket_213590Z.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FarmFreshMarket_213590Z.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<AuthUser> _signInManager;
        private readonly IHttpContextAccessor _contxt;

        public LogoutModel(IHttpContextAccessor httpContextAccessor, SignInManager<AuthUser> signInManager)
        {
            _signInManager = signInManager;
            _contxt = httpContextAccessor;
        }
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                _signInManager.SignOutAsync();
                _contxt.HttpContext.Session.Clear();
            }
            return RedirectToPage("Index");
        }
        //clear session
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            _signInManager.SignOutAsync();
            _contxt.HttpContext.Session.Clear();
            return RedirectToPage("Login");
        }
        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }

    }
}

FarmFreshMarket_213590Z/Pages/Privacy.cshtml.cs
using FarmFreshMarket_213590Z.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web.Lib;

namespace FarmFreshMarket_213590Z.Pages
{
    
    public class PrivacyModel : PageModel
    {
        private readonly UserManager<AuthUser> _userManager;
        private readonly IHttpContextAccessor _http;
        public AuthUser retrieveuser { get; set; } = new();
        public string username { get; set; }


        public PrivacyModel(IHttpContextAccessor http, UserManager<AuthUser> userManager)
        {
            _userManager = userManager;
            _http = http;

        }

        public async Task<IActionResult> OnGetAsync()
        {
            //retrieve the Session Data
            username = _http.HttpContext?.Session.GetString(SessionVariable.UserName);
            if (username == null)
            {
                return RedirectToPage("Index");
            }
            return Page();
        }
    }
}

FarmFreshMarket_213590Z/Pages/Register.cshtml.cs
using FarmFreshMarket_213590Z.Models;
using FarmFreshMarket_213590Z.Models;
using FarmFreshMarket_213590Z.Services;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Text;
using Web.Lib;

namespace FarmFreshMarket_213590Z.Pages
{
    public class RegisterModel : PageModel
    {
        private UserManager<AuthUser> userManager { get; }
        private SignInManager<AuthUser> signInManager { get; }

        private IWebHostEnvironment _environment;
        private RoleManager<IdentityRole> roleManager { get; }

        private readonly IDataProtector _protector;
        private readonly IHttpContextAccessor _contxt;

        [BindProperty]
        public AuthUser RModel { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{12,}$", ErrorMessage = "Use a minimum of 12 characters, including lower-case and upper-case , numbers and special characters")]
        public string Password { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        [BindProperty]
        public IFormFile? Upload { get; set; }

        [BindProperty]
        public string Register { get; set; }

        public RegisterModel(IHttpContextAccessor httpContextAccessor, 
            IDataProtectionProvider provider, 
            UserManager<AuthUser> userManager, SignInManager<AuthUser> signInManager, IWebHostEnvironment environment, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _environment = environment;
            _contxt = httpContextAccessor;
            _protector = provider.CreateProtector("credit_card_protector");
            this.roleManager = roleManager;
            //_resetPasswordService = resetPasswordService;

        }

        public void OnGet()
        {



        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OnPostAsync()
        {
            //upload image
            if (ModelState.IsValid)
            {
                //for all other data
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptDara");
                

                if (Upload != null)
                {
                    if (Upload.Length > 2097152)
                    {
                        ModelState.AddModelError("Upload", "File size cannot exceed 2MB.");
                        return Page();
                    }

                    var uploadsFolder = "uploads";
                    var imageFile = Guid.NewGuid() + Path.GetExtension(Upload.FileName);
                    var imagePath = Path.Combine(_environment.ContentRootPath, "wwwroot", uploadsFolder, imageFile);
                    using var fileStream = new FileStream(imagePath, FileMode.Create);
                    await Upload.CopyToAsync(fileStream);
                    var ImageURL = string.Format("/" + uploadsFolder + "/" + imageFile);

                    //protect data
                    var protectedCreditCardNumber = _protector.Protect(RModel.CreditCardNumber);
                    var protectedUserName = _protector.Protect(System.Web.HttpUtility.HtmlEncode(EmailAddress));
                    var protectedPassword = _protector.Protect(System.Web.HttpUtility.HtmlEncode(Password));
                    var protectedFullName = _protector.Protect(System.Web.HttpUtility.HtmlEncode(RModel.FullName));
                    var protectedGender = _protector.Protect(System.Web.HttpUtility.HtmlEncode(RModel.Gender));
                    var protectedEmail = _protector.Protect(System.Web.HttpUtility.HtmlEncode(EmailAddress));
                    var protectedPhoneNo = _protector.Protect(System.Web.HttpUtility.HtmlEncode(RModel.PhoneNumber));
                    var protectedAddress = _protector.Protect(System.Web.HttpUtility.HtmlEncode(RModel.DeliveryAddress));
                    var protectedAboutMe = _protector.Protect(System.Web.HttpUtility.HtmlEncode(RModel.AboutMe));



                    //pass data to database
                    var user = new AuthUser
                    {
                        UserName = EmailAddress,
                        Photo = ImageURL,
                        FullName = RModel.FullName,
                        Gender = RModel.Gender,
                        Email = EmailAddress,
                        PhoneNumber = "+65 " + RModel.PhoneNumber,
                        DeliveryAddress = RModel.DeliveryAddress,
                        CreditCardNumber = protectedCreditCardNumber,
                        AboutMe = RModel.AboutMe
                    };

                    //check duplicate email
                    var enteredEmail = await userManager.FindByEmailAsync(EmailAddress);

                    if (enteredEmail != null)
                    {
                        ModelState.AddModelError(EmailAddress, "This email has already been registered");
                        return Page();
                    }

                    var result = await userManager.CreateAsync(user, Password);
                    if (result.Succeeded)
                    {
                        await roleManager.CreateAsync(new IdentityRole("Admin"));
                        if(user.Email == "ZHIYI@gmail.com")
                        {
                            await userManager.AddToRoleAsync(user, "Admin");
                        }
                        return RedirectToPage("Login");
                    }

                    // show error message in page
                    foreach (var e in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, e.Description);
                    }

                }
            }
            return Page();
        }



    }
}

FarmFreshMarket_213590Z/Pages/TestLog.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FarmFreshMarket_213590Z.Pages
{
    [Authorize(Roles ="Admin")]
    public class TestLogModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

FarmFreshMarket_213590Z/Pages/UserProfile.cshtml.cs
using FarmFreshMarket_213590Z.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web.Lib;

namespace FarmFreshMarket_213590Z.Pages
{
    
    public class UserProfileModel : PageModel
    {
        private readonly UserManager<AuthUser> _userManager;
        private readonly IDataProtector _protector;
        private readonly IHttpContextAccessor _http;

        public AuthUser retrieveuser { get; set; }
        public string username { get; set; }


        public UserProfileModel(IHttpContextAccessor httpAccessor,UserManager<AuthUser> userManager, IDataProtectionProvider DataProProvider)
        {
            _userManager = userManager;
            _protector = DataProProvider.CreateProtector("credit_card_protector");
            _http = httpAccessor;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            //retrieve the Session Data
            username = _http.HttpContext?.Session.GetString(SessionVariable.UserName);
            if (username == null)
            {
                return RedirectToPage("Index");
            }
            var finduser = await _userManager.FindByEmailAsync(username);


          //decrypt the Credit Card
            var decryptedCreditCardNumber = _protector.Unprotect(finduser.CreditCardNumber);
            finduser.CreditCardNumber = decryptedCreditCardNumber;
            retrieveuser = finduser;

           
       

            return Page();
        }
       
    }
}

FarmFreshMarket_213590Z/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Application Security Assignment</h1>
   
</div>

FarmFreshMarket_213590Z/Pages/Login.cshtml
@page

@model FarmFreshMarket_213590Z.Pages.LoginModel
@using Microsoft.Extensions.Options
@using FarmFreshMarket_213590Z.Models
@inject IOptions<GoogleCaptchaConfig> GoogleCaptchaConfig

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post" asp-page-handler="InHouse">
				<div asp-validation-summary="All" class="text-danger"></div>
				<input type="hidden" id="CaptchaToken" asp-for="LModel.Token"/>
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validation-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validation-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>
				
			</form>
			@*<form method="post" class="d-grid gap-3" asp-page-handler="Google">
                <button type="submit" class="btn btn-secondary">Login use Google Account</button>
            </form>*@
			<div>
				<p>Did you forget your Password ?<a asp-page="/ForgetPassword"> Reset Here</a></p>
			</div>
		</div>
	</div>
</div>

<script src="https://www.google.com/recaptcha/api.js?render=@GoogleCaptchaConfig.Value.SiteKey"></script>

<script>
      
document.addEventListener("DOMContentLoaded", function() {
	grecaptcha.ready(function() {
			grecaptcha.execute('@GoogleCaptchaConfig.Value.SiteKey', {action: 'submit'}).then(function(token) {
				// Add your logic to submit to your backend server here.
				console.log(token)
				document.getElementById("CaptchaToken").value = token
			});
	});
	
});
</script>

FarmFreshMarket_213590Z/Pages/Logout.cshtml
@page
@model FarmFreshMarket_213590Z.Pages.LogoutModel
@{
}

FarmFreshMarket_213590Z/Pages/Register.cshtml
@page
@model FarmFreshMarket_213590Z.Pages.RegisterModel
@{
}

<section class="h-100">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <div class="card card-registration my-4">
                    <div class="row g-0">

                        <div class="col-xl-12 align-content-center">
                            <div class="card-body p-md-5 text-black">
                                <h3 class="mb-5 text-uppercase"> registration</h3>
                                <form method="post" enctype="multipart/form-data">
                                    <input type="hidden" asp-for="Register" class="form-control" value="Register" />
                                    
                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="RModel.FullName">Full Name</label>
                                            <input type="Text" asp-for="RModel.FullName" class="form-control" />
                                            <span asp-validation-for="RModel.FullName" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="Upload">Profile Image</label>
                                            <input type="file" accept="image/*" asp-for="Upload" class="form-control" onchange="showImgPreview(this)" />
                                            <span asp-validation-for="Upload" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="RModel.Gender">Gender</label><br />
                                            <div class="form-check form-check-inline mb-0 me-4">
                                                <input type="radio" asp-for="RModel.Gender" value="male" /> Male
                                            </div>
                                            <div class="form-check form-check-inline mb-0 me-4">
                                                <input type="radio" asp-for="RModel.Gender" value="female" /> Female
                                            </div>

                                            <span asp-validation-for="RModel.Gender" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6 mb-4">
                                            <div class="form-outline">
                                                <label class="form-label" asp-for="EmailAddress">Email Address</label>
                                                <input type="Text" asp-for="EmailAddress" class="form-control" />
                                                <span asp-validation-for="EmailAddress" class="text-danger"></span>
                                                <span asp-validation-for="Register" class="text-danger"></span>
                                            </div>
                                        </div>

                                        <div class="col-md-6 mb-4">
                                            <div class="form-outline">
                                                <label class="form-label" asp-for="RModel.PhoneNumber">Phone Number</label>
                                                <input type="Text" asp-for="RModel.PhoneNumber" class="form-control" />
                                                <span asp-validation-for="RModel.PhoneNumber" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="Password">Password</label>
                                            <input type="Text" asp-for="Password" class="form-control" id="password" onblur="validatePassword()"/>
                                            <p id="passwordValid" class="visually-hidden text-danger" >Passwords must contain a combination of lower-case, upper-case, numbers, and special characters and have a minimum length of 12 characters.</p>
                                            <span asp-validation-for="Password" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="ConfirmPassword">Confirm Password</label>
                                            <input type="Text" asp-for="ConfirmPassword" class="form-control" />
                                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="RModel.DeliveryAddress">Delivery Address</label>
                                            <input type="Text" asp-for="RModel.DeliveryAddress" class="form-control" />
                                            <span asp-validation-for="RModel.DeliveryAddress" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="RModel.CreditCardNumber">Credit Card Number</label>
                                            <input type="text" asp-for="RModel.CreditCardNumber" class="form-control" />
                                            <span asp-validation-for="RModel.CreditCardNumber" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" asp-for="RModel.AboutMe">About Me</label>
                                            <textarea type="text" asp-for="RModel.AboutMe" class="form-control"></textarea>
                                            <span asp-validation-for="RModel.AboutMe" class="text-danger"></span>
                                        </div>
                                    </div>
      
                                    <div class="d-flex justify-content-end pt-3">
                                        <button type="submit" class="btn btn-primary">Sign Up</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">

       

function validatePassword() {
    var passwordInput = document.getElementById("password");
    // Get the password value
    var password = passwordInput.value;

    // Regular expression to check for the use of lower-case, upper-case, numbers, and special characters
    var complexityRegex =/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{12,}$/;

    // Check if the password meets the complexity requirements
    if (!password.match(complexityRegex)) {
            //0passwordValid.classlist.remove("visually-hidden")
       alert("Passwords must contain a combination of lower-case, upper-case, numbers, and special characters and have a minimum length of 12 characters.");
    }
}
    

</script>

FarmFreshMarket_213590Z/Pages/TestLog.cshtml
@page
@model FarmFreshMarket_213590Z.Pages.TestLogModel
@{
}

<p> You are able to see logs as you are a admin</p>

FarmFreshMarket_213590Z/Pages/UserProfile.cshtml
@page
@using FarmFreshMarket_213590Z.Models
@using Microsoft.AspNetCore.Identity
@model FarmFreshMarket_213590Z.Pages.UserProfileModel
@inject IHttpContextAccessor contxt
@inject SignInManager<AuthUser> SignInManager
@{

}

<div class="text-center">
    <h1 class="alert-dark">User Profile</h1>
</div>

@{
    if (SignInManager.IsSignedIn(User))
    {
               
                    <div class="card">
                <img class="card-img-top" style="width: 50%; height: 50%" src="@Model.retrieveuser.Photo" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@Model.retrieveuser.FullName</h5>
                            <p class="card-text">About Me: @Model.retrieveuser.AboutMe</p>
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">Gender: @Model.retrieveuser.Gender</li>
                                    <li class="list-group-item">Email: @Model.retrieveuser.Email</li>
                                    <li class="list-group-item">Credit Card Number: @Model.retrieveuser.CreditCardNumber</li>
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
    }
    
}